### ISSUE TITLE
Infusion counter error on generated builds

### ISSUE THREAD

**Issue by dani5703** [SaculRennorb/HsBuildCodes#14]
Teapot generated a build code on his stream last night (using his bot, not PlenBot) and the number of power (Mighty) infusions on the generated build is incorrect.

Build link: 
```https://hardstuck.gg/gw2/builds/?b=DwHn~b1~X8~bAxUWGSVWFxUWBSVWMiKS1JykCxkCzVK0UWhCGIJFhCEIJ2jKH_B2jKM5VV__```

Currently: 19 Mighty Infusions, 1 Enrichment
What it should be: 20 Mighty Infusions, 1 Enrichment

**Comment by SaculRennorb** [comment]
Interesting. the code isn't even compressed. 
Any chance of figuring out which items doesn't get processed properly? like put different infusions into equipment and figure out which infusion is missing in the build code in the end.
