### ISSUE TITLE
One of the pets from ranger builds are missing in generated codes

### ISSUE THREAD

**Issue by dani5703** [SaculRennorb/HsBuildCodes#16]
When generating a build code for ranger (specifically druid in my case) one of the pets dont show up in the generated build, alongside of the missing stats from most of the weapon/trinket pieces.
I was using Iboga and Gazelle in this generated build, but only the Gazelle shows up.

Build:
[Link to the build](https://hardstuck.gg/gw2/builds/?b=DoDI~-Z~tF~6PTqRWJSATqRJWJSNUFPDDSDDRDDZEDKEGA~KNQBTVBA~D~__9~7~)

**Comment by SaculRennorb** [comment]
This appears to be something different entirely, the buildcode link actually redirects to the heal druid link. That might be messing some things up. I have to look into how that redirect happens to figure out where its going wrong.

**Comment by SaculRennorb** [comment]
Should be closed by 05aa3e3b2df2701c1d90280eb736dbc93d294d70 and will update on beta shortly for testing.
